### ISSUE TITLE
index/list API calls do not work

### ISSUE THREAD

**Issue by realdlee** [HashNuke/mailgun#39]
You get the following error: 

ArgumentError: options must be a hash.

I traced the error to the JSON gem.  

Two possible fixes:

1. use JSON.parse directly in base.rb
https://github.com/flori/json/blob/master/lib/json/common.rb#L466
2. pass an empty hash to `JSON(RestClient.send(method, url, parameters))`
https://github.com/HashNuke/mailgun/blob/master/lib/mailgun/base.rb#L75

![screen shot 2015-06-19 at 6 48 22 pm](https://cloud.githubusercontent.com/assets/1109290/8265596/dc08975a-16b3-11e5-95f1-5aed065dd630.png)

**Comment by HashNuke** [comment]
@realdlee thanks for debugging this.
If you can send a PR and test it out, I'll merge it in.
