### ISSUE TITLE
undefined method `addresses' for #<Mailgun::Base:0x007fc2c1dd8cf0>

### ISSUE THREAD

**Issue by 9mm** [HashNuke/mailgun#54]
I'm trying to validate an email according to the docs, but I keep getting this error. I thought maybe the docs are out of date but after digging I'm not actually sure how to call it properly.

**Comment by 9mm** [comment]
It appears because the hosted gem version is so insanely old... is this even maintained anymore? Can we get a fresh version on rubygems?

**Comment by HashNuke** [comment]
@9mm I'll release a version today. Thanks for reminding me.

**Comment by 9mm** [comment]
Awesome, thanks

**Comment by 9mm** [comment]
Any luck with this?

**Comment by HashNuke** [comment]
@9mm published 0.11 to rubygems. Thanks for giving me the push.

Closing this issue.
